/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.FacAprobador;
import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.domain.MtrAprobador;
import com.incloud.hcp.domain.response.FacAprobadorResponse;
import com.incloud.hcp.repository.delta.FacAprobadorDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.FacAprobadorDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class FacAprobadorRest extends JPACustomRest<FacAprobadorResponse, FacAprobador, Integer> {

    @Autowired
    protected FacAprobadorDeltaService facAprobadorDeltaService;

    @Autowired
    protected FacAprobadorDeltaRepository facAprobadorDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "FacAprobador";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final FacAprobador createInstance() {
        FacAprobador facAprobador = new FacAprobador();
        return facAprobador;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo facFactura.
    */
    @ApiOperation(value = "Contador de registros para el atributo facFactura", produces = "application/json")
    @PostMapping(value = "/countByFacFactura", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByFacFactura(@RequestBody @Valid FacFactura facFactura, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByFacFactura");
        try {
            return Optional.ofNullable(this.facAprobadorDeltaService.countByFacFactura(facFactura)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo facFactura.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo facFactura", produces = "application/json")
    @GetMapping(value = "/graphByFacFactura", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByFacFactura() throws URISyntaxException {
        log.debug("Ingresando graphByFacFactura");
        try {
            return Optional.ofNullable(this.facAprobadorDeltaService.graphByFacFactura()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrAprobador.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrAprobador", produces = "application/json")
    @PostMapping(value = "/countByMtrAprobador", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrAprobador(@RequestBody @Valid MtrAprobador mtrAprobador, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrAprobador");
        try {
            return Optional.ofNullable(this.facAprobadorDeltaService.countByMtrAprobador(mtrAprobador)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrAprobador.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrAprobador", produces = "application/json")
    @GetMapping(value = "/graphByMtrAprobador", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrAprobador() throws URISyntaxException {
        log.debug("Ingresando graphByMtrAprobador");
        try {
            return Optional.ofNullable(this.facAprobadorDeltaService.graphByMtrAprobador()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
