/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.MareaEvento;
import com.incloud.hcp.domain.MtrEstado;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.MtrZonaPesca;
import com.incloud.hcp.domain.response.MareaEventoResponse;
import com.incloud.hcp.repository.delta.MareaEventoDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.MareaEventoDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class MareaEventoRest extends JPACustomRest<MareaEventoResponse, MareaEvento, Integer> {

    @Autowired
    protected MareaEventoDeltaService mareaEventoDeltaService;

    @Autowired
    protected MareaEventoDeltaRepository mareaEventoDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MareaEvento";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MareaEvento createInstance() {
        MareaEvento mareaEvento = new MareaEvento();
        return mareaEvento;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo mtrEstado.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrEstado", produces = "application/json")
    @PostMapping(value = "/countByMtrEstado", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrEstado(@RequestBody @Valid MtrEstado mtrEstado, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrEstado");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.countByMtrEstado(mtrEstado)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrEstado.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrEstado", produces = "application/json")
    @GetMapping(value = "/graphByMtrEstado", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrEstado() throws URISyntaxException {
        log.debug("Ingresando graphByMtrEstado");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.graphByMtrEstado()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrZonaPesca.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrZonaPesca", produces = "application/json")
    @PostMapping(value = "/countByMtrZonaPesca", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrZonaPesca(@RequestBody @Valid MtrZonaPesca mtrZonaPesca, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrZonaPesca");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.countByMtrZonaPesca(mtrZonaPesca)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrZonaPesca.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrZonaPesca", produces = "application/json")
    @GetMapping(value = "/graphByMtrZonaPesca", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrZonaPesca() throws URISyntaxException {
        log.debug("Ingresando graphByMtrZonaPesca");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.graphByMtrZonaPesca()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrTipoEvento.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrTipoEvento", produces = "application/json")
    @PostMapping(value = "/countByMtrTipoEvento", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrTipoEvento(@RequestBody @Valid MtrTipoEvento mtrTipoEvento, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrTipoEvento");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.countByMtrTipoEvento(mtrTipoEvento)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrTipoEvento.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrTipoEvento", produces = "application/json")
    @GetMapping(value = "/graphByMtrTipoEvento", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrTipoEvento() throws URISyntaxException {
        log.debug("Ingresando graphByMtrTipoEvento");
        try {
            return Optional.ofNullable(this.mareaEventoDeltaService.graphByMtrTipoEvento()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
