/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.MareaPesca;
import com.incloud.hcp.domain.MtrEmbarcacion;
import com.incloud.hcp.domain.MtrHorometro;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.response.MareaPescaResponse;
import com.incloud.hcp.repository.delta.MareaPescaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.MareaPescaDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class MareaPescaRest extends JPACustomRest<MareaPescaResponse, MareaPesca, Integer> {

    @Autowired
    protected MareaPescaDeltaService mareaPescaDeltaService;

    @Autowired
    protected MareaPescaDeltaRepository mareaPescaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MareaPesca";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MareaPesca createInstance() {
        MareaPesca mareaPesca = new MareaPesca();
        return mareaPesca;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo mtrEmbarcacion.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrEmbarcacion", produces = "application/json")
    @PostMapping(value = "/countByMtrEmbarcacion", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrEmbarcacion(@RequestBody @Valid MtrEmbarcacion mtrEmbarcacion, BindingResult bindingResult)
            throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrEmbarcacion");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.countByMtrEmbarcacion(mtrEmbarcacion)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrEmbarcacion.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrEmbarcacion", produces = "application/json")
    @GetMapping(value = "/graphByMtrEmbarcacion", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrEmbarcacion() throws URISyntaxException {
        log.debug("Ingresando graphByMtrEmbarcacion");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.graphByMtrEmbarcacion()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrTipoEvento.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrTipoEvento", produces = "application/json")
    @PostMapping(value = "/countByMtrTipoEvento", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrTipoEvento(@RequestBody @Valid MtrTipoEvento mtrTipoEvento, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrTipoEvento");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.countByMtrTipoEvento(mtrTipoEvento)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrTipoEvento.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrTipoEvento", produces = "application/json")
    @GetMapping(value = "/graphByMtrTipoEvento", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrTipoEvento() throws URISyntaxException {
        log.debug("Ingresando graphByMtrTipoEvento");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.graphByMtrTipoEvento()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrHorometro.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrHorometro", produces = "application/json")
    @PostMapping(value = "/countByMtrHorometro", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrHorometro(@RequestBody @Valid MtrHorometro mtrHorometro, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrHorometro");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.countByMtrHorometro(mtrHorometro)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrHorometro.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrHorometro", produces = "application/json")
    @GetMapping(value = "/graphByMtrHorometro", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrHorometro() throws URISyntaxException {
        log.debug("Ingresando graphByMtrHorometro");
        try {
            return Optional.ofNullable(this.mareaPescaDeltaService.graphByMtrHorometro()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
