/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrEmbarcacion;
import com.incloud.hcp.domain.response.MtrEmbarcacionResponse;
import com.incloud.hcp.repository.delta.MtrEmbarcacionDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrEmbarcacionRest extends JPACustomRest<MtrEmbarcacionResponse, MtrEmbarcacion, Integer> {

    @Autowired
    protected MtrEmbarcacionDeltaRepository mtrEmbarcacionDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrEmbarcacion";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrEmbarcacion createInstance() {
        MtrEmbarcacion mtrEmbarcacion = new MtrEmbarcacion();
        return mtrEmbarcacion;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
