/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrHorometro;
import com.incloud.hcp.domain.response.MtrHorometroResponse;
import com.incloud.hcp.repository.delta.MtrHorometroDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrHorometroRest extends JPACustomRest<MtrHorometroResponse, MtrHorometro, Integer> {

    @Autowired
    protected MtrHorometroDeltaRepository mtrHorometroDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrHorometro";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrHorometro createInstance() {
        MtrHorometro mtrHorometro = new MtrHorometro();
        return mtrHorometro;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
