/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.response.MtrTipoEventoResponse;
import com.incloud.hcp.repository.delta.MtrTipoEventoDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrTipoEventoRest extends JPACustomRest<MtrTipoEventoResponse, MtrTipoEvento, Integer> {

    @Autowired
    protected MtrTipoEventoDeltaRepository mtrTipoEventoDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrTipoEvento";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrTipoEvento createInstance() {
        MtrTipoEvento mtrTipoEvento = new MtrTipoEvento();
        return mtrTipoEvento;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
