/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrTipoPesca;
import com.incloud.hcp.domain.response.MtrTipoPescaResponse;
import com.incloud.hcp.repository.delta.MtrTipoPescaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrTipoPescaRest extends JPACustomRest<MtrTipoPescaResponse, MtrTipoPesca, Integer> {

    @Autowired
    protected MtrTipoPescaDeltaRepository mtrTipoPescaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrTipoPesca";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrTipoPesca createInstance() {
        MtrTipoPesca mtrTipoPesca = new MtrTipoPesca();
        return mtrTipoPesca;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
