/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/support/PageRequestByExample.java.p.vm
 */
package com.incloud.hcp.service.support;

import org.apache.commons.lang.StringUtils;
import org.springframework.data.domain.Pageable;

public class PageRequestByExample<DTO> {
    private final int ROWS_DEFAULT = 1000;
    public DTO example;
    public LazyLoadEvent lazyLoadEvent;

    public Pageable toPageable() {
        return lazyLoadEvent != null ? lazyLoadEvent.toPageable() : null;
    }

    public void generarLazyDefecto(String sortField) {
        if (this.lazyLoadEvent == null) {
            this.lazyLoadEvent = new LazyLoadEvent();
            this.lazyLoadEvent.first = 0;
            this.lazyLoadEvent.rows = ROWS_DEFAULT;
            this.lazyLoadEvent.sortField = sortField;
            this.lazyLoadEvent.sortOrder = 1;
        } else {
            if (StringUtils.isBlank(this.lazyLoadEvent.sortField)) {
                this.lazyLoadEvent.sortField = sortField;
                this.lazyLoadEvent.sortOrder = 1;
            }
            if (this.lazyLoadEvent.rows == 0) {
                this.lazyLoadEvent.rows = ROWS_DEFAULT;
            }
        }
    }
}