/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.CerFirma;
import com.incloud.hcp.domain.CerNotaPedido;
import com.incloud.hcp.domain.MtrAprobador;
import com.incloud.hcp.domain.MtrTipoFirma;
import com.incloud.hcp.repository.CerFirmaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface CerFirmaDeltaRepository extends CerFirmaRepository {

    @Query("select u.cerNotaPedido from CerFirma u where " +
            " u.cerNotaPedido.id in ?1 and " +
            " u.mtrAprobador.id= ?2 " +
            " order by u.cerNotaPedido.fechaDocumento desc, u.cerNotaPedido.codigoNotaPedidoSap" )
    List<CerNotaPedido> findByCerNotaPedidoMtrAprobador(
            List<Integer> cerNotaPedidoList,
            Integer mtrAprobadorId
    );

    List<CerFirma> findByCerNotaPedidoInAndMtrAprobadorAndMtrTipoFirma(
            List<CerNotaPedido> cerNotaPedidoList,
            MtrAprobador mtrAprobador,
            MtrTipoFirma mtrTipoFirma
    );

    List<CerFirma> findByCerNotaPedidoAndMtrAprobadorAndMtrTipoFirma(
            CerNotaPedido cerNotaPedido,
            MtrAprobador mtrAprobador,
            MtrTipoFirma mtrTipoFirma
    );

    @Query("select u from CerFirma u where u.mtrAprobador.id= ?1 " +
            "and u.mtrTipoFirma.id = ?2 " +
            "and u.cerNotaPedido.mtrEstado.codigoEstado IN ('NPVI','NPCE','NPVG')")
    List<CerFirma> findByMtrAprobadorAndMtrTipoFirmaVigentes(
            Integer mtrAprobadorId,
            Integer mtrTipoFirmaId
    );

    @Query("select u.mtrAprobador from CerFirma u where u.cerNotaPedido.id = ?1 and u.mtrTipoFirma.id = ?2")
    List<MtrAprobador> devuelveAprobadorByNotaPedidoAndTipoFirma(
            Integer cerNotaPedidoId,
            Integer mtrTipoFirmaId
    );


    List<CerFirma> findByCerNotaPedido(CerNotaPedido cerNotaPedido);

    @Modifying
    @Query("DELETE FROM CerFirma f WHERE f.ebeln= ?1")
    void deleteByEbeln(String ebeln);

    @Query("select f from CerFirma f where f.cerNotaPedido.id = ?1 and f.mtrTipoFirma.id = ?2 and f.mtrAprobador.id = ?3")
    CerFirma getByUniqueCode(Integer pedido, Integer tipoFirma, Integer aprobador);

    @Query("select f from CerFirma f where f.cerNotaPedido.id = ?1")
    List<CerFirma> getByCodeNotaPedido(Integer idNotaPedido);

    @Query("select u from CerFirma u where u.cerNotaPedido.id = ?1 and u.mtrTipoFirma.codigoTipoFirma = ?2")
    List<CerFirma> findByNotaPedidoAndTipoFirma(Integer cerNotaPedidoId, String codigoTipoFirma);


}
