/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.repository.FacFacturaRepository;
import org.springframework.data.jpa.repository.Query;

public interface FacFacturaDeltaRepository extends FacFacturaRepository {

    @Query("select c from FacFactura c " +
            "where c.mtrProveedor.id = ?1 " +
            "and c.tipoFactura = ?2 " +
            "and c.serieFactura = ?3 " +
            "and c.numeroFactura = ?4")
    FacFactura verificarExisteNumeroDocumentoFactura(
            Integer idProveedor,
            String tipoDocumento,
            String serie,
            String numero);

}
