/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntitydeltaResource.java.e.vm
 */
package com.incloud.hcp.rest.delta;

import com.incloud.hcp.domain.FacAprobador;
import com.incloud.hcp.rest.FacAprobadorRest;
import com.incloud.hcp.service.delta.FacAprobadorDeltaService;
import io.swagger.annotations.ApiOperation;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/api/facAprobador")
public class FacAprobadorDeltaRest extends FacAprobadorRest {

    private final Logger log = LoggerFactory.getLogger(FacAprobadorDeltaRest.class);

    @Autowired
    protected FacAprobadorDeltaService facAprobadorDeltaService;

    @ApiOperation(value = "Listado Criterio FacAprobador", produces = "application/json")
    @RequestMapping(value = "/listCriterioFacAprobador", method = RequestMethod.POST, headers = "Accept=application/json")
    ResponseEntity<List<FacAprobador>> listCriterioFacAprobador(@RequestBody FacAprobador facAprobador)
            throws Exception {
        return Optional.of(new ResponseEntity<List<FacAprobador>>(
                this.facAprobadorDeltaService .find(facAprobador),
                HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
    }

}
