/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.MareaPesca;
import com.incloud.hcp.domain.MtrEmbarcacion;
import com.incloud.hcp.domain.MtrHorometro;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.response.MareaPescaResponse;
import com.incloud.hcp.service._framework.JPACustomService;

/**
 * Simple Interface for MareaPesca.
 */
public interface MareaPescaService extends JPACustomService<MareaPescaResponse, MareaPesca, Integer> {

    Long countByMtrEmbarcacion(MtrEmbarcacion mtrEmbarcacion);

    GraphBean graphByMtrEmbarcacion();

    Long countByMtrTipoEvento(MtrTipoEvento mtrTipoEvento);

    GraphBean graphByMtrTipoEvento();

    Long countByMtrHorometro(MtrHorometro mtrHorometro);

    GraphBean graphByMtrHorometro();

}
