/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.MareaEvento;
import com.incloud.hcp.domain.MtrEstado;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.MtrZonaPesca;
import com.incloud.hcp.domain.response.MareaEventoResponse;
import com.incloud.hcp.service._framework.JPACustomService;

/**
 * Simple Interface for MareaEvento.
 */
public interface MareaEventoService extends JPACustomService<MareaEventoResponse, MareaEvento, Integer> {

    Long countByMtrEstado(MtrEstado mtrEstado);

    GraphBean graphByMtrEstado();

    Long countByMtrZonaPesca(MtrZonaPesca mtrZonaPesca);

    GraphBean graphByMtrZonaPesca();

    Long countByMtrTipoEvento(MtrTipoEvento mtrTipoEvento);

    GraphBean graphByMtrTipoEvento();

}
