/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.MtrHorometro;
import com.incloud.hcp.domain.MtrHorometro_;
import com.incloud.hcp.domain.response.MtrHorometroResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.MtrHorometroDeltaRepository;
import com.incloud.hcp.service.MtrHorometroService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.requireNew.MtrHorometroRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for MtrHorometro.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class MtrHorometroServiceImpl extends JPACustomServiceImpl<MtrHorometroResponse, MtrHorometro, Integer> implements MtrHorometroService {

    protected final String NAME_SHEET = "MtrHorometro";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/MtrHorometroExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected MtrHorometroDeltaRepository mtrHorometroDeltaRepository;

    @Autowired
    protected MtrHorometroRequireNewService mtrHorometroRequireNewService;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(MtrHorometro_.nombre.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(MtrHorometro req, ExampleMatcher matcher, Example<MtrHorometro> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<MtrHorometro> req, ExampleMatcher matcher, Example<MtrHorometro> example);

    protected final MtrHorometro setObtenerBeanResponse(MtrHorometroResponse bean) {
        return bean.getBean();
    }

    protected final Class<MtrHorometro> setObtenerClassBean() {
        return MtrHorometro.class;
    }

    protected List<Predicate> setAbstractPredicate(MtrHorometroResponse bean, CriteriaBuilder cb, Root<MtrHorometro> root) {
        List<Predicate> predicates = new ArrayList<>();
        MtrHorometro entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getNombreCondicion(), "nombre", entity.getNombre(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "nombre", bean.getNombreList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(MtrHorometro bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getNombre()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrHorometro.nombre.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(MtrHorometro bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(MtrHorometro bean) throws Exception {
        String msg = null;
        MtrHorometro validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(MtrHorometro bean) throws Exception {
        String msg = null;
        MtrHorometro validar = null;
        return msg;
    }

    protected MtrHorometro completarDatosBean(MtrHorometro bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected MtrHorometro setCompletarDatosBean(MtrHorometro bean) throws Exception {
        return bean;
    }

    protected final MtrHorometro setAbstractCreate(MtrHorometro dto) throws Exception {
        MtrHorometro bean = new MtrHorometro();
        bean = (MtrHorometro) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrHorometro setUploadExcel(Cell currentCell, MtrHorometro mtrHorometro, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 100) {
                    throw new ServiceException("Valor Campo nombre contiene mas de 100 caracter(es)");
                }
                mtrHorometro.setNombre(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo nombre está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return mtrHorometro;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected MtrHorometro setInicializarBeanUpdateExcel() {
        MtrHorometro bean = new MtrHorometro();
        bean.setId(null);
        return bean;
    }

    protected final Integer setObtenerId(MtrHorometro bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final MtrHorometro createInstance() {
        MtrHorometro mtrHorometro = new MtrHorometro();
        return mtrHorometro;
    }

    protected final BeanCargaMasivoDTO<MtrHorometro> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<MtrHorometro> beanCargaMasivoDTO = new BeanCargaMasivoDTO<MtrHorometro>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrHorometro>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrHorometro>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrHorometro>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(MtrHorometro bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getNombre(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(MtrHorometro bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getNombre(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(MtrHorometro bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO MTR_HOROMETRO(";
        sqlInsert = sqlInsert + "MTR_HOROMETRO_ID" + ", ";
        sqlInsert = sqlInsert + "NOMBRE" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        if (StringUtils.isBlank(bean.getNombre())) {
            sqlInsert = sqlInsert + "null";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getNombre() + "'";
        }
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
