/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.MtrSector;
import com.incloud.hcp.domain.MtrSector_;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;

import java.util.List;

@NoRepositoryBean
public interface MtrSectorRepository extends JPACustomRepository<MtrSector, Integer> {

    /**
     * Return the persistent instance of {@link MtrSector} with the given unique property value codigoSector,
     * or null if there is no such persistent instance.
     *
     * @param codigoSector the unique value
     * @return the corresponding {@link MtrSector} persistent instance or null
     */
    @RestResource(path = "/getByCodigoSector")
    MtrSector getByCodigoSector(@Param("codigoSector") String codigoSector);

    /**
     * Return the persistent instance of {@link MtrSector} with the given unique property value descripcion,
     * or null if there is no such persistent instance.
     *
     * @param descripcion the unique value
     * @return the corresponding {@link MtrSector} persistent instance or null
     */
    @RestResource(path = "/getByDescripcion")
    MtrSector getByDescripcion(@Param("descripcion") String descripcion);

    default List<MtrSector> findCompletePaginated(String query, int maxResults) {
        MtrSector probe = new MtrSector();
        //probe.setDescripcion(query);
        probe.setDescripcion(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(MtrSector_.descripcion.getName(), match -> match.ignoreCase().startsWith());

        Page<MtrSector> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

}
