/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.FacContacto;
import com.incloud.hcp.domain.MtrSector;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.List;

/**
 * Simple Interface for FacContacto.
 */
@Data
@ToString
@EqualsAndHashCode
public class FacContactoResponse extends BaseResponseDomain<FacContacto> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String usuarioCondicion;
    private String contactoNombresCondicion;
    private String contactoApellidosCondicion;
    private String emailCondicion;
    private String tipoContactoCondicion;
    private String activoCondicion;
    private String estadoCondicion;
    private String codigoIdpCondicion;
    //private String mtrSectorCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<String> usuarioList;
    private List<String> contactoNombresList;
    private List<String> contactoApellidosList;
    private List<String> emailList;
    private List<String> tipoContactoList;
    private List<String> activoList;
    private List<String> estadoList;
    private List<String> codigoIdpList;
    private List<MtrSector> mtrSectorList;

}
