/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.List;

/**
 * Simple Interface for MareaPesca.
 */
@Data
@ToString
@EqualsAndHashCode
public class MareaPescaResponse extends BaseResponseDomain<MareaPesca> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String numeroMareaCondicion;
    private String valorHorometroCondicion;
    //private String mtrEmbarcacionCondicion;
    //private String mtrTipoEventoCondicion;
    //private String mtrHorometroCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<String> numeroMareaList;
    private List<BigDecimal> valorHorometroList;
    private List<MtrEmbarcacion> mtrEmbarcacionList;
    private List<MtrTipoEvento> mtrTipoEventoList;
    private List<MtrHorometro> mtrHorometroList;

}
