/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "fac_aprobador", uniqueConstraints = { @UniqueConstraint(name = "fac_aprobador_ak01", columnNames = { "fac_factura_id", "mtr_aprobador_id" }) })
//@Audited
//@AuditTable("_audi_fac_aprobador")
public class FacAprobador extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(FacAprobador.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String estado;

    // Many to one
    private FacFactura facFactura;
    private MtrAprobador mtrAprobador;

    @Override
    public String entityClassName() {
        return FacAprobador.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "fac_aprobador_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_fac_aprobador")
    @Id
    @SequenceGenerator(name = "seq_fac_aprobador", sequenceName = "seq_fac_aprobador", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public FacAprobador id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [estado] ------------------------

    @NotEmpty(message = "{message.facAprobador.estado.requerido}")
    @Size(max = 1, message = "{message.facAprobador.estado.sizeMax} {max} {message.caracter}")
    @Column(name = "estado", nullable = false, length = 1)
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public FacAprobador estado(String estado) {
        setEstado(estado);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FacAprobador.facFactura ==> FacFactura.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "fac_factura_id", nullable = false)
    @ManyToOne
    public FacFactura getFacFactura() {
        return facFactura;
    }

    /**
     * Set the {@link #facFactura} without adding this FacAprobador instance on the passed {@link #facFactura}
     */
    public void setFacFactura(FacFactura facFactura) {
        this.facFactura = facFactura;
    }

    public FacAprobador facFactura(FacFactura facFactura) {
        setFacFactura(facFactura);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FacAprobador.mtrAprobador ==> MtrAprobador.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_aprobador_id", nullable = false)
    @ManyToOne
    public MtrAprobador getMtrAprobador() {
        return mtrAprobador;
    }

    /**
     * Set the {@link #mtrAprobador} without adding this FacAprobador instance on the passed {@link #mtrAprobador}
     */
    public void setMtrAprobador(MtrAprobador mtrAprobador) {
        this.mtrAprobador = mtrAprobador;
    }

    public FacAprobador mtrAprobador(MtrAprobador mtrAprobador) {
        setMtrAprobador(mtrAprobador);
        return this;
    }

    /**
     * Apply the default values.
     */
    public FacAprobador withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof FacAprobador && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this FacAprobador instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("facFactura", getFacFactura()) //    
                .add("mtrAprobador", getMtrAprobador()) //    
                .add("estado", getEstado()) //
                .toString();
    }
}
