/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(FacContacto.class)
public abstract class FacContacto_ {

    // Raw attributes
    public static volatile SingularAttribute<FacContacto, Integer> id;
    public static volatile SingularAttribute<FacContacto, String> usuario;
    public static volatile SingularAttribute<FacContacto, String> contactoNombres;
    public static volatile SingularAttribute<FacContacto, String> contactoApellidos;
    public static volatile SingularAttribute<FacContacto, String> email;
    public static volatile SingularAttribute<FacContacto, String> tipoContacto;
    public static volatile SingularAttribute<FacContacto, String> activo;
    public static volatile SingularAttribute<FacContacto, String> estado;
    public static volatile SingularAttribute<FacContacto, String> codigoIdp;

    // Many to one
    public static volatile SingularAttribute<FacContacto, MtrSector> mtrSector;
}
