/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.incloud.hcp.annotation.ExtendedEmailValidator;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "fac_contacto")
//@Audited
//@AuditTable("_audi_fac_contacto")
public class FacContacto extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(FacContacto.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String usuario;
    private String contactoNombres;
    private String contactoApellidos;
    private String email;
    private String tipoContacto;
    private String activo;
    private String estado;
    private String codigoIdp;

    // Many to one
    private MtrSector mtrSector;

    @Override
    public String entityClassName() {
        return FacContacto.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "fac_contacto_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_fac_contacto")
    @Id
    @SequenceGenerator(name = "seq_fac_contacto", sequenceName = "seq_fac_contacto", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public FacContacto id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [usuario] ------------------------

    @NotEmpty(message = "{message.facContacto.usuario.requerido}")
    @Size(max = 25, message = "{message.facContacto.usuario.sizeMax} {max} {message.caracter}")
    @Column(name = "usuario", nullable = false, unique = true, length = 25)
    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public FacContacto usuario(String usuario) {
        setUsuario(usuario);
        return this;
    }
    // -- [contactoNombres] ------------------------

    @NotEmpty(message = "{message.facContacto.contactoNombres.requerido}")
    @Size(max = 50, message = "{message.facContacto.contactoNombres.sizeMax} {max} {message.caracter}")
    @Column(name = "contacto_nombres", nullable = false, length = 50)
    public String getContactoNombres() {
        return contactoNombres;
    }

    public void setContactoNombres(String contactoNombres) {
        this.contactoNombres = contactoNombres;
    }

    public FacContacto contactoNombres(String contactoNombres) {
        setContactoNombres(contactoNombres);
        return this;
    }
    // -- [contactoApellidos] ------------------------

    @NotEmpty(message = "{message.facContacto.contactoApellidos.requerido}")
    @Size(max = 50, message = "{message.facContacto.contactoApellidos.sizeMax} {max} {message.caracter}")
    @Column(name = "contacto_apellidos", nullable = false, length = 50)
    public String getContactoApellidos() {
        return contactoApellidos;
    }

    public void setContactoApellidos(String contactoApellidos) {
        this.contactoApellidos = contactoApellidos;
    }

    public FacContacto contactoApellidos(String contactoApellidos) {
        setContactoApellidos(contactoApellidos);
        return this;
    }
    // -- [email] ------------------------

    @ExtendedEmailValidator
    @NotEmpty(message = "{message.facContacto.email.requerido}")
    @Size(max = 100, message = "{message.facContacto.email.sizeMax} {max} {message.caracter}")
    @Column(name = "email", nullable = false, unique = true, length = 100)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public FacContacto email(String email) {
        setEmail(email);
        return this;
    }
    // -- [tipoContacto] ------------------------

    @Size(max = 3, message = "{message.facContacto.tipoContacto.sizeMax} {max} {message.caracter}")
    @Column(name = "tipo_contacto", length = 3)
    public String getTipoContacto() {
        return tipoContacto;
    }

    public void setTipoContacto(String tipoContacto) {
        this.tipoContacto = tipoContacto;
    }

    public FacContacto tipoContacto(String tipoContacto) {
        setTipoContacto(tipoContacto);
        return this;
    }
    // -- [activo] ------------------------

    @Size(max = 1, message = "{message.facContacto.activo.sizeMax} {max} {message.caracter}")
    @Column(name = "activo", length = 1)
    public String getActivo() {
        return activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }

    public FacContacto activo(String activo) {
        setActivo(activo);
        return this;
    }
    // -- [estado] ------------------------

    @Size(max = 1, message = "{message.facContacto.estado.sizeMax} {max} {message.caracter}")
    @Column(name = "estado", length = 1)
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public FacContacto estado(String estado) {
        setEstado(estado);
        return this;
    }
    // -- [codigoIdp] ------------------------

    @Size(max = 20, message = "{message.facContacto.codigoIdp.sizeMax} {max} {message.caracter}")
    @Column(name = "codigo_idp", length = 20)
    public String getCodigoIdp() {
        return codigoIdp;
    }

    public void setCodigoIdp(String codigoIdp) {
        this.codigoIdp = codigoIdp;
    }

    public FacContacto codigoIdp(String codigoIdp) {
        setCodigoIdp(codigoIdp);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FacContacto.mtrSector ==> MtrSector.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_sector_id", nullable = false)
    @ManyToOne
    public MtrSector getMtrSector() {
        return mtrSector;
    }

    /**
     * Set the {@link #mtrSector} without adding this FacContacto instance on the passed {@link #mtrSector}
     */
    public void setMtrSector(MtrSector mtrSector) {
        this.mtrSector = mtrSector;
    }

    public FacContacto mtrSector(MtrSector mtrSector) {
        setMtrSector(mtrSector);
        return this;
    }

    /**
     * Apply the default values.
     */
    public FacContacto withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof FacContacto && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getUsuario());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this FacContacto instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("usuario", getUsuario()) //
                .add("contactoNombres", getContactoNombres()) //
                .add("contactoApellidos", getContactoApellidos()) //
                .add("email", getEmail()) //
                .add("tipoContacto", getTipoContacto()) //
                .add("activo", getActivo()) //
                .add("estado", getEstado()) //
                .add("mtrSector", getMtrSector()) //    
                .add("codigoIdp", getCodigoIdp()) //
                .toString();
    }
}
