/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "fac_imputacion", uniqueConstraints = {
        @UniqueConstraint(name = "fac_imputacion_ak01", columnNames = { "fac_factura_id", "mtr_cuenta_imputacion_id" }) })
//@Audited
//@AuditTable("_audi_fac_imputacion")
public class FacImputacion extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(FacImputacion.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private BigDecimal valorImputacion;
    private String estado;

    // Many to one
    private MtrCuentaImputacion mtrCuentaImputacion;
    private FacFactura facFactura;

    @Override
    public String entityClassName() {
        return FacImputacion.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "fac_imputacion_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_fac_imputacion")
    @Id
    @SequenceGenerator(name = "seq_fac_imputacion", sequenceName = "seq_fac_imputacion", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public FacImputacion id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [valorImputacion] ------------------------

    @Digits(integer = 16, fraction = 2)
    @NotNull
    @Column(name = "valor_imputacion", nullable = false, precision = 18, scale = 2)
    public BigDecimal getValorImputacion() {
        return valorImputacion;
    }

    public void setValorImputacion(BigDecimal valorImputacion) {
        this.valorImputacion = valorImputacion;
    }

    public FacImputacion valorImputacion(BigDecimal valorImputacion) {
        setValorImputacion(valorImputacion);
        return this;
    }
    // -- [estado] ------------------------

    @NotEmpty(message = "{message.facImputacion.estado.requerido}")
    @Size(max = 1, message = "{message.facImputacion.estado.sizeMax} {max} {message.caracter}")
    @Column(name = "estado", nullable = false, length = 1)
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public FacImputacion estado(String estado) {
        setEstado(estado);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FacImputacion.mtrCuentaImputacion ==> MtrCuentaImputacion.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_cuenta_imputacion_id", nullable = false)
    @ManyToOne
    public MtrCuentaImputacion getMtrCuentaImputacion() {
        return mtrCuentaImputacion;
    }

    /**
     * Set the {@link #mtrCuentaImputacion} without adding this FacImputacion instance on the passed {@link #mtrCuentaImputacion}
     */
    public void setMtrCuentaImputacion(MtrCuentaImputacion mtrCuentaImputacion) {
        this.mtrCuentaImputacion = mtrCuentaImputacion;
    }

    public FacImputacion mtrCuentaImputacion(MtrCuentaImputacion mtrCuentaImputacion) {
        setMtrCuentaImputacion(mtrCuentaImputacion);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: FacImputacion.facFactura ==> FacFactura.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "fac_factura_id", nullable = false)
    @ManyToOne
    public FacFactura getFacFactura() {
        return facFactura;
    }

    /**
     * Set the {@link #facFactura} without adding this FacImputacion instance on the passed {@link #facFactura}
     */
    public void setFacFactura(FacFactura facFactura) {
        this.facFactura = facFactura;
    }

    public FacImputacion facFactura(FacFactura facFactura) {
        setFacFactura(facFactura);
        return this;
    }

    /**
     * Apply the default values.
     */
    public FacImputacion withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof FacImputacion && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this FacImputacion instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("facFactura", getFacFactura()) //    
                .add("mtrCuentaImputacion", getMtrCuentaImputacion()) //    
                .add("valorImputacion", getValorImputacion()) //
                .add("estado", getEstado()) //
                .toString();
    }
}
