/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;
import static javax.persistence.TemporalType.TIMESTAMP;

@Entity
@Table(name = "marea_evento")
//@Audited
//@AuditTable("_audi_MAREA_EVENTO")
public class MareaEvento extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MareaEvento.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private Date fechaEvento;
    private String horaVento;
    private BigDecimal stock;

    // Many to one
    private MtrEstado mtrEstado;
    private MtrZonaPesca mtrZonaPesca;
    private MtrTipoEvento mtrTipoEvento;

    @Override
    public String entityClassName() {
        return MareaEvento.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "marea_evento_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_marea_evento")
    @Id
    @SequenceGenerator(name = "seq_marea_evento", sequenceName = "seq_marea_evento", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MareaEvento id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [fechaEvento] ------------------------

    @NotNull
    @Column(name = "fecha_evento", nullable = false, length = 29)

    @Temporal(TIMESTAMP)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    public Date getFechaEvento() {
        return fechaEvento;
    }

    public void setFechaEvento(Date fechaEvento) {
        this.fechaEvento = fechaEvento;
    }

    public MareaEvento fechaEvento(Date fechaEvento) {
        setFechaEvento(fechaEvento);
        return this;
    }
    // -- [horaVento] ------------------------

    @NotEmpty(message = "{message.mareaEvento.horaVento.requerido}")
    @Size(max = 10, message = "{message.mareaEvento.horaVento.sizeMax} {max} {message.caracter}")
    @Column(name = "hora_vento", nullable = false, length = 10)
    public String getHoraVento() {
        return horaVento;
    }

    public void setHoraVento(String horaVento) {
        this.horaVento = horaVento;
    }

    public MareaEvento horaVento(String horaVento) {
        setHoraVento(horaVento);
        return this;
    }
    // -- [stock] ------------------------

    @Digits(integer = 17, fraction = 2)
    @Column(name = "stock", precision = 19, scale = 2)
    public BigDecimal getStock() {
        return stock;
    }

    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }

    public MareaEvento stock(BigDecimal stock) {
        setStock(stock);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaEvento.mtrEstado ==> MtrEstado.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "mtr_estado_id")
    @ManyToOne
    public MtrEstado getMtrEstado() {
        return mtrEstado;
    }

    /**
     * Set the {@link #mtrEstado} without adding this MareaEvento instance on the passed {@link #mtrEstado}
     */
    public void setMtrEstado(MtrEstado mtrEstado) {
        this.mtrEstado = mtrEstado;
    }

    public MareaEvento mtrEstado(MtrEstado mtrEstado) {
        setMtrEstado(mtrEstado);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaEvento.mtrZonaPesca ==> MtrZonaPesca.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "mtr_zona_pesca_id")
    @ManyToOne
    public MtrZonaPesca getMtrZonaPesca() {
        return mtrZonaPesca;
    }

    /**
     * Set the {@link #mtrZonaPesca} without adding this MareaEvento instance on the passed {@link #mtrZonaPesca}
     */
    public void setMtrZonaPesca(MtrZonaPesca mtrZonaPesca) {
        this.mtrZonaPesca = mtrZonaPesca;
    }

    public MareaEvento mtrZonaPesca(MtrZonaPesca mtrZonaPesca) {
        setMtrZonaPesca(mtrZonaPesca);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaEvento.mtrTipoEvento ==> MtrTipoEvento.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_tipo_evento_id", nullable = false)
    @ManyToOne
    public MtrTipoEvento getMtrTipoEvento() {
        return mtrTipoEvento;
    }

    /**
     * Set the {@link #mtrTipoEvento} without adding this MareaEvento instance on the passed {@link #mtrTipoEvento}
     */
    public void setMtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        this.mtrTipoEvento = mtrTipoEvento;
    }

    public MareaEvento mtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        setMtrTipoEvento(mtrTipoEvento);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MareaEvento withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MareaEvento && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this MareaEvento instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("mtrTipoEvento", getMtrTipoEvento()) //    
                .add("fechaEvento", getFechaEvento()) //
                .add("horaVento", getHoraVento()) //
                .add("mtrZonaPesca", getMtrZonaPesca()) //    
                .add("mtrEstado", getMtrEstado()) //    
                .add("stock", getStock()) //
                .toString();
    }
}
