/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "MAREA_PESCA")
//@Audited
//@AuditTable("_audi_MAREA_PESCA")
public class MareaPesca extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MareaPesca.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String numeroMarea;
    private BigDecimal valorHorometro;

    // Many to one
    private MtrEmbarcacion mtrEmbarcacion;
    private MtrTipoEvento mtrTipoEvento;
    private MtrHorometro mtrHorometro;

    @Override
    public String entityClassName() {
        return MareaPesca.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "MAREA_PESCA_ID", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_MAREA_PESCA")
    @Id
    @SequenceGenerator(name = "seq_MAREA_PESCA", sequenceName = "seq_MAREA_PESCA", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MareaPesca id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [numeroMarea] ------------------------

    @NotEmpty(message = "{message.mareaPesca.numeroMarea.requerido}")
    @Size(max = 100, message = "{message.mareaPesca.numeroMarea.sizeMax} {max} {message.caracter}")
    @Column(name = "NUMERO_MAREA", nullable = false, length = 100)
    public String getNumeroMarea() {
        return numeroMarea;
    }

    public void setNumeroMarea(String numeroMarea) {
        this.numeroMarea = numeroMarea;
    }

    public MareaPesca numeroMarea(String numeroMarea) {
        setNumeroMarea(numeroMarea);
        return this;
    }
    // -- [valorHorometro] ------------------------

    @Digits(integer = 17, fraction = 2)
    @Column(name = "VALOR_HOROMETRO", precision = 19, scale = 2)
    public BigDecimal getValorHorometro() {
        return valorHorometro;
    }

    public void setValorHorometro(BigDecimal valorHorometro) {
        this.valorHorometro = valorHorometro;
    }

    public MareaPesca valorHorometro(BigDecimal valorHorometro) {
        setValorHorometro(valorHorometro);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaPesca.mtrEmbarcacion ==> MtrEmbarcacion.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "MTR_EMBARCACION_ID", nullable = false)
    @ManyToOne
    public MtrEmbarcacion getMtrEmbarcacion() {
        return mtrEmbarcacion;
    }

    /**
     * Set the {@link #mtrEmbarcacion} without adding this MareaPesca instance on the passed {@link #mtrEmbarcacion}
     */
    public void setMtrEmbarcacion(MtrEmbarcacion mtrEmbarcacion) {
        this.mtrEmbarcacion = mtrEmbarcacion;
    }

    public MareaPesca mtrEmbarcacion(MtrEmbarcacion mtrEmbarcacion) {
        setMtrEmbarcacion(mtrEmbarcacion);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaPesca.mtrTipoEvento ==> MtrTipoEvento.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "MTR_TIPO_EVENTO_ID", nullable = false)
    @ManyToOne
    public MtrTipoEvento getMtrTipoEvento() {
        return mtrTipoEvento;
    }

    /**
     * Set the {@link #mtrTipoEvento} without adding this MareaPesca instance on the passed {@link #mtrTipoEvento}
     */
    public void setMtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        this.mtrTipoEvento = mtrTipoEvento;
    }

    public MareaPesca mtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        setMtrTipoEvento(mtrTipoEvento);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: MareaPesca.mtrHorometro ==> MtrHorometro.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "MTR_HOROMETRO_ID")
    @ManyToOne
    public MtrHorometro getMtrHorometro() {
        return mtrHorometro;
    }

    /**
     * Set the {@link #mtrHorometro} without adding this MareaPesca instance on the passed {@link #mtrHorometro}
     */
    public void setMtrHorometro(MtrHorometro mtrHorometro) {
        this.mtrHorometro = mtrHorometro;
    }

    public MareaPesca mtrHorometro(MtrHorometro mtrHorometro) {
        setMtrHorometro(mtrHorometro);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MareaPesca withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MareaPesca && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this MareaPesca instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("numeroMarea", getNumeroMarea()) //
                .add("mtrEmbarcacion", getMtrEmbarcacion()) //    
                .add("mtrHorometro", getMtrHorometro()) //    
                .add("valorHorometro", getValorHorometro()) //
                .add("mtrTipoEvento", getMtrTipoEvento()) //    
                .toString();
    }
}
