/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;

@StaticMetamodel(MareaPesca.class)
public abstract class MareaPesca_ {

    // Raw attributes
    public static volatile SingularAttribute<MareaPesca, Integer> id;
    public static volatile SingularAttribute<MareaPesca, String> numeroMarea;
    public static volatile SingularAttribute<MareaPesca, BigDecimal> valorHorometro;

    // Many to one
    public static volatile SingularAttribute<MareaPesca, MtrEmbarcacion> mtrEmbarcacion;
    public static volatile SingularAttribute<MareaPesca, MtrTipoEvento> mtrTipoEvento;
    public static volatile SingularAttribute<MareaPesca, MtrHorometro> mtrHorometro;
}
