/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;
import java.util.Date;

@StaticMetamodel(MareaEvento.class)
public abstract class MareaEvento_ {

    // Raw attributes
    public static volatile SingularAttribute<MareaEvento, Integer> id;
    public static volatile SingularAttribute<MareaEvento, Date> fechaEvento;
    public static volatile SingularAttribute<MareaEvento, String> horaVento;
    public static volatile SingularAttribute<MareaEvento, BigDecimal> stock;

    // Many to one
    public static volatile SingularAttribute<MareaEvento, MtrEstado> mtrEstado;
    public static volatile SingularAttribute<MareaEvento, MtrZonaPesca> mtrZonaPesca;
    public static volatile SingularAttribute<MareaEvento, MtrTipoEvento> mtrTipoEvento;
}
