/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "mtr_sector")
//@Audited
//@AuditTable("_audi_mtr_sector")
public class MtrSector extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MtrSector.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String codigoSector;
    private String descripcion;

    @Override
    public String entityClassName() {
        return MtrSector.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "mtr_sector_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_mtr_sector")
    @Id
    @SequenceGenerator(name = "seq_mtr_sector", sequenceName = "seq_mtr_sector", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MtrSector id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoSector] ------------------------

    @NotEmpty(message = "{message.mtrSector.codigoSector.requerido}")
    @Size(max = 10, message = "{message.mtrSector.codigoSector.sizeMax} {max} {message.caracter}")
    @Column(name = "codigo_sector", nullable = false, unique = true, length = 10)
    public String getCodigoSector() {
        return codigoSector;
    }

    public void setCodigoSector(String codigoSector) {
        this.codigoSector = codigoSector;
    }

    public MtrSector codigoSector(String codigoSector) {
        setCodigoSector(codigoSector);
        return this;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.mtrSector.descripcion.requerido}")
    @Size(max = 100, message = "{message.mtrSector.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "descripcion", nullable = false, unique = true, length = 100)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public MtrSector descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MtrSector withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MtrSector && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getDescripcion());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this MtrSector instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codigoSector", getCodigoSector()) //
                .add("descripcion", getDescripcion()) //
                .toString();
    }
}
