/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MareaEvento;
import com.incloud.hcp.domain.MtrEstado;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.MtrZonaPesca;
import com.incloud.hcp.domain.response.MareaEventoResponse;
import com.incloud.hcp.service.delta.MareaEventoDeltaService;
import com.incloud.hcp.service.impl.MareaEventoServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MareaEvento.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MareaEventoDeltaServiceImpl extends MareaEventoServiceImpl implements MareaEventoDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(MareaEvento req, ExampleMatcher matcher, Example<MareaEvento> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MareaEvento> req, ExampleMatcher matcher, Example<MareaEvento> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MareaEventoResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MareaEvento> query, Root<MareaEvento> root) throws Exception {

        MareaEvento entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MareaEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MareaEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MareaEvento> setAdicionalDeltaTotalPredicate(MareaEventoResponse bean, Root<MareaEvento> countRoot) throws Exception {
        MareaEvento entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MareaEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MareaEvento bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MareaEvento setCreate(MareaEvento bean) throws Exception {
        return bean;
    }

    protected void setSave(MareaEvento dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MareaEvento setUploadExcel(Cell currentCell, MareaEvento mareaEvento, int contador) throws Exception {
        mareaEvento = super.setUploadExcel(currentCell, mareaEvento, contador);
        return mareaEvento;
    }

    protected String setSaveMasivo(MareaEvento dto) throws Exception {
        return "";
    }

    protected List<MareaEvento> setBeforeDeleteMasivo(List<MareaEvento> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MareaEvento bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByMtrEstado(MtrEstado mtrEstado) {
        return mtrEstado.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrEstado() {
        return "MtrEstado";
    }

    protected String setGraphBarChartTituloByMtrEstado() {
        return "MtrEstado";
    }

    protected String setGraphDescripcionByMtrZonaPesca(MtrZonaPesca mtrZonaPesca) {
        return mtrZonaPesca.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrZonaPesca() {
        return "MtrZonaPesca";
    }

    protected String setGraphBarChartTituloByMtrZonaPesca() {
        return "MtrZonaPesca";
    }

    protected String setGraphDescripcionByMtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        return mtrTipoEvento.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrTipoEvento() {
        return "MtrTipoEvento";
    }

    protected String setGraphBarChartTituloByMtrTipoEvento() {
        return "MtrTipoEvento";
    }

}
