/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MareaPesca;
import com.incloud.hcp.domain.MtrEmbarcacion;
import com.incloud.hcp.domain.MtrHorometro;
import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.response.MareaPescaResponse;
import com.incloud.hcp.service.delta.MareaPescaDeltaService;
import com.incloud.hcp.service.impl.MareaPescaServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MareaPesca.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MareaPescaDeltaServiceImpl extends MareaPescaServiceImpl implements MareaPescaDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(MareaPesca req, ExampleMatcher matcher, Example<MareaPesca> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MareaPesca> req, ExampleMatcher matcher, Example<MareaPesca> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MareaPescaResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MareaPesca> query, Root<MareaPesca> root) throws Exception {

        MareaPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MareaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MareaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MareaPesca> setAdicionalDeltaTotalPredicate(MareaPescaResponse bean, Root<MareaPesca> countRoot) throws Exception {
        MareaPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MareaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MareaPesca bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MareaPesca setCreate(MareaPesca bean) throws Exception {
        return bean;
    }

    protected void setSave(MareaPesca dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MareaPesca setUploadExcel(Cell currentCell, MareaPesca mareaPesca, int contador) throws Exception {
        mareaPesca = super.setUploadExcel(currentCell, mareaPesca, contador);
        return mareaPesca;
    }

    protected String setSaveMasivo(MareaPesca dto) throws Exception {
        return "";
    }

    protected List<MareaPesca> setBeforeDeleteMasivo(List<MareaPesca> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MareaPesca bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByMtrEmbarcacion(MtrEmbarcacion mtrEmbarcacion) {
        return mtrEmbarcacion.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrEmbarcacion() {
        return "MtrEmbarcacion";
    }

    protected String setGraphBarChartTituloByMtrEmbarcacion() {
        return "MtrEmbarcacion";
    }

    protected String setGraphDescripcionByMtrTipoEvento(MtrTipoEvento mtrTipoEvento) {
        return mtrTipoEvento.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrTipoEvento() {
        return "MtrTipoEvento";
    }

    protected String setGraphBarChartTituloByMtrTipoEvento() {
        return "MtrTipoEvento";
    }

    protected String setGraphDescripcionByMtrHorometro(MtrHorometro mtrHorometro) {
        return mtrHorometro.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrHorometro() {
        return "MtrHorometro";
    }

    protected String setGraphBarChartTituloByMtrHorometro() {
        return "MtrHorometro";
    }

}
