/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrAprobador;
import com.incloud.hcp.service.delta.MtrAprobadorDeltaService;
import com.incloud.hcp.service.impl.MtrAprobadorServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * A simple DTO Facility for MtrAprobador.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrAprobadorDeltaServiceImpl extends MtrAprobadorServiceImpl implements MtrAprobadorDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "aprobadorSap")
        );
        return sort;
    }

    protected Sort setFind(MtrAprobador req, ExampleMatcher matcher, Example<MtrAprobador> example, Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "aprobadorSap")
        );
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrAprobador> req, ExampleMatcher matcher, Example<MtrAprobador> example) {
        return;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrAprobador bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrAprobador setCreate(MtrAprobador bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrAprobador dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrAprobador setUploadExcel(Cell currentCell, MtrAprobador mtrAprobador, int contador) throws Exception {
        mtrAprobador = super.setUploadExcel(currentCell, mtrAprobador, contador);
        return mtrAprobador;
    }

    protected String setSaveMasivo(MtrAprobador dto) throws Exception {
        return "";
    }

    protected List<MtrAprobador> setBeforeDeleteMasivo(List<MtrAprobador> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrAprobador bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
