/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrTipoPesca;
import com.incloud.hcp.domain.response.MtrTipoPescaResponse;
import com.incloud.hcp.service.delta.MtrTipoPescaDeltaService;
import com.incloud.hcp.service.impl.MtrTipoPescaServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrTipoPesca.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrTipoPescaDeltaServiceImpl extends MtrTipoPescaServiceImpl implements MtrTipoPescaDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected Sort setFind(MtrTipoPesca req, ExampleMatcher matcher, Example<MtrTipoPesca> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrTipoPesca> req, ExampleMatcher matcher, Example<MtrTipoPesca> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrTipoPescaResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrTipoPesca> query, Root<MtrTipoPesca> root) throws Exception {

        MtrTipoPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrTipoPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrTipoPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrTipoPesca> setAdicionalDeltaTotalPredicate(MtrTipoPescaResponse bean, Root<MtrTipoPesca> countRoot) throws Exception {
        MtrTipoPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrTipoPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrTipoPesca bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrTipoPesca setCreate(MtrTipoPesca bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrTipoPesca dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrTipoPesca setUploadExcel(Cell currentCell, MtrTipoPesca mtrTipoPesca, int contador) throws Exception {
        mtrTipoPesca = super.setUploadExcel(currentCell, mtrTipoPesca, contador);
        return mtrTipoPesca;
    }

    protected String setSaveMasivo(MtrTipoPesca dto) throws Exception {
        return "";
    }

    protected List<MtrTipoPesca> setBeforeDeleteMasivo(List<MtrTipoPesca> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrTipoPesca bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
