/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrTipoEvento;
import com.incloud.hcp.domain.response.MtrTipoEventoResponse;
import com.incloud.hcp.service.delta.MtrTipoEventoDeltaService;
import com.incloud.hcp.service.impl.MtrTipoEventoServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrTipoEvento.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrTipoEventoDeltaServiceImpl extends MtrTipoEventoServiceImpl implements MtrTipoEventoDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected Sort setFind(MtrTipoEvento req, ExampleMatcher matcher, Example<MtrTipoEvento> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrTipoEvento> req, ExampleMatcher matcher, Example<MtrTipoEvento> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrTipoEventoResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrTipoEvento> query, Root<MtrTipoEvento> root) throws Exception {

        MtrTipoEvento entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrTipoEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrTipoEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrTipoEvento> setAdicionalDeltaTotalPredicate(MtrTipoEventoResponse bean, Root<MtrTipoEvento> countRoot) throws Exception {
        MtrTipoEvento entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrTipoEvento, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrTipoEvento bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrTipoEvento setCreate(MtrTipoEvento bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrTipoEvento dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrTipoEvento setUploadExcel(Cell currentCell, MtrTipoEvento mtrTipoEvento, int contador) throws Exception {
        mtrTipoEvento = super.setUploadExcel(currentCell, mtrTipoEvento, contador);
        return mtrTipoEvento;
    }

    protected String setSaveMasivo(MtrTipoEvento dto) throws Exception {
        return "";
    }

    protected List<MtrTipoEvento> setBeforeDeleteMasivo(List<MtrTipoEvento> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrTipoEvento bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
