/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrZonaPesca;
import com.incloud.hcp.domain.response.MtrZonaPescaResponse;
import com.incloud.hcp.service.delta.MtrZonaPescaDeltaService;
import com.incloud.hcp.service.impl.MtrZonaPescaServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrZonaPesca.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrZonaPescaDeltaServiceImpl extends MtrZonaPescaServiceImpl implements MtrZonaPescaDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected Sort setFind(MtrZonaPesca req, ExampleMatcher matcher, Example<MtrZonaPesca> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombre"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrZonaPesca> req, ExampleMatcher matcher, Example<MtrZonaPesca> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrZonaPescaResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrZonaPesca> query, Root<MtrZonaPesca> root) throws Exception {

        MtrZonaPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrZonaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrZonaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrZonaPesca> setAdicionalDeltaTotalPredicate(MtrZonaPescaResponse bean, Root<MtrZonaPesca> countRoot) throws Exception {
        MtrZonaPesca entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrZonaPesca, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrZonaPesca bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrZonaPesca setCreate(MtrZonaPesca bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrZonaPesca dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrZonaPesca setUploadExcel(Cell currentCell, MtrZonaPesca mtrZonaPesca, int contador) throws Exception {
        mtrZonaPesca = super.setUploadExcel(currentCell, mtrZonaPesca, contador);
        return mtrZonaPesca;
    }

    protected String setSaveMasivo(MtrZonaPesca dto) throws Exception {
        return "";
    }

    protected List<MtrZonaPesca> setBeforeDeleteMasivo(List<MtrZonaPesca> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrZonaPesca bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
